/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	lib "github.com/bborbe/agent/lib"
)

// ScheduleTemplateApplyConfiguration represents a declarative configuration of the ScheduleTemplate type for use
// with apply.
//
// ScheduleTemplate is the body + frontmatter the generated task carries.
type ScheduleTemplateApplyConfiguration struct {
	// Body is raw markdown. Free-form; not validated.
	Body *string `json:"body,omitempty"`
	// Frontmatter is the YAML frontmatter of the generated vault file.
	// Reuses lib.TaskFrontmatter from github.com/bborbe/agent/lib.
	Frontmatter *lib.TaskFrontmatter `json:"frontmatter,omitempty"`
}

// ScheduleTemplateApplyConfiguration constructs a declarative configuration of the ScheduleTemplate type for use with
// apply.
func ScheduleTemplate() *ScheduleTemplateApplyConfiguration {
	return &ScheduleTemplateApplyConfiguration{}
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *ScheduleTemplateApplyConfiguration) WithBody(
	value string,
) *ScheduleTemplateApplyConfiguration {
	b.Body = &value
	return b
}

// WithFrontmatter sets the Frontmatter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Frontmatter field is set to the value of the last call.
func (b *ScheduleTemplateApplyConfiguration) WithFrontmatter(
	value lib.TaskFrontmatter,
) *ScheduleTemplateApplyConfiguration {
	b.Frontmatter = &value
	return b
}
