/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ScheduleSpecApplyConfiguration represents a declarative configuration of the ScheduleSpec type for use
// with apply.
//
// ScheduleSpec is the spec of a Schedule.
type ScheduleSpecApplyConfiguration struct {
	// Vault is the Obsidian vault slug the generated task lives in.
	// Constrained to ^[a-z][a-z0-9-]*$ by the OpenAPI schema (enforced at
	// the API-server boundary via SetupCustomResourceDefinition in
	// pkg/k8s_connector.go).
	Vault *string `json:"vault,omitempty"`
	// Title is the title shown to the user.
	Title *string `json:"title,omitempty"`
	// Schedule describes when the task fires. The weekday-required-iff-weekly
	// invariant is encoded as a CEL x-kubernetes-validations rule in
	// scheduleSpecSchema (Prompt 2).
	Schedule *ScheduleTriggerApplyConfiguration `json:"schedule,omitempty"`
	// Template is the body + frontmatter stamped onto the generated task.
	Template *ScheduleTemplateApplyConfiguration `json:"template,omitempty"`
}

// ScheduleSpecApplyConfiguration constructs a declarative configuration of the ScheduleSpec type for use with
// apply.
func ScheduleSpec() *ScheduleSpecApplyConfiguration {
	return &ScheduleSpecApplyConfiguration{}
}

// WithVault sets the Vault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vault field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithVault(value string) *ScheduleSpecApplyConfiguration {
	b.Vault = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithTitle(value string) *ScheduleSpecApplyConfiguration {
	b.Title = &value
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithSchedule(value *ScheduleTriggerApplyConfiguration) *ScheduleSpecApplyConfiguration {
	b.Schedule = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithTemplate(value *ScheduleTemplateApplyConfiguration) *ScheduleSpecApplyConfiguration {
	b.Template = value
	return b
}
