/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ScheduleTriggerApplyConfiguration represents a declarative configuration of the ScheduleTrigger type for use
// with apply.
//
// ScheduleTrigger is the recurrence subnode.
type ScheduleTriggerApplyConfiguration struct {
	// Recurrence is one of: "Daily", "Weekly", "Weekday", "Monthly", "Quarterly", "Yearly"
	// (capitalized, matching Go's time.Weekday.String() style and Spec 6/9's
	// period-token output). "Weekly" is always-fire (no weekday); "Weekday"
	// fires only on its target weekday. Constrained by the OpenAPI enum in
	// scheduleSpecSchema.
	Recurrence *string `json:"recurrence,omitempty"`
	// Weekday is required when Recurrence == "Weekday"; forbidden otherwise.
	// Values are time.Weekday.String() form: "Monday", "Tuesday", "Wednesday",
	// "Thursday", "Friday", "Saturday", "Sunday". Encoded as the CEL rule in
	// scheduleSpecSchema. The Go type is `string` (not `*string`) so JSON
	// omits the field cleanly when unset; the schema's presence check is
	// `has(self.weekday)`. Optionality is encoded by `omitempty` + the CEL
	// rule — no separate `+optional` marker is needed.
	Weekday *string `json:"weekday,omitempty"`
}

// ScheduleTriggerApplyConfiguration constructs a declarative configuration of the ScheduleTrigger type for use with
// apply.
func ScheduleTrigger() *ScheduleTriggerApplyConfiguration {
	return &ScheduleTriggerApplyConfiguration{}
}

// WithRecurrence sets the Recurrence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Recurrence field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithRecurrence(
	value string,
) *ScheduleTriggerApplyConfiguration {
	b.Recurrence = &value
	return b
}

// WithWeekday sets the Weekday field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weekday field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithWeekday(
	value string,
) *ScheduleTriggerApplyConfiguration {
	b.Weekday = &value
	return b
}
