/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ScheduleTriggerApplyConfiguration represents a declarative configuration of the ScheduleTrigger type for use
// with apply.
//
// ScheduleTrigger is the recurrence subnode.
type ScheduleTriggerApplyConfiguration struct {
	// Recurrence is one of: "Daily", "Weekly", "Weekday", "Monthly", "Quarterly", "Yearly"
	// (capitalized, matching Go's time.Weekday.String() style and Spec 6/9's
	// period-token output). "Weekly" is always-fire (no weekday); "Weekday"
	// fires only on its target weekday. Constrained by the OpenAPI enum in
	// scheduleSpecSchema.
	Recurrence *string `json:"recurrence,omitempty"`
	// Weekday is a single weekday (long form Monday..Sunday). Set when
	// Recurrence == "Weekday" and the schedule targets exactly one day;
	// mutually exclusive with Weekdays (the CEL XOR rule in
	// scheduleTriggerSchema enforces exactly-one-of on Weekday recurrence,
	// neither otherwise). Normalized to a canonical time.Weekday Go-side by
	// the store adapter.
	Weekday *string `json:"weekday,omitempty"`
	// Weekdays is a non-empty list of weekdays (long form Monday..Sunday or
	// short form Mon..Sun, mixable). Set when Recurrence == "Weekday" and the
	// schedule targets multiple days; mutually exclusive with Weekday.
	// Normalized and deduplicated to a canonical time.Weekday set Go-side by
	// the store adapter.
	Weekdays []string `json:"weekdays,omitempty"`
	// PeriodOffset shifts the period-anchored token by N periods. Default 0
	// (current period). Negative values name a prior period; positive values
	// name a future period. The shift applies to the period token suffix
	// appended to the task title AND the UUID5 input — so a Monthly schedule
	// firing on 2026-07-01 with PeriodOffset=-1 produces token "2026-06" and
	// the task is named "<title> - 2026-06". Body placeholders ({{current_month}}
	// etc.) render against the unshifted fire date — this is intentional.
	//
	// Only valid for Recurrence in {Monthly, Quarterly, Yearly}. Non-zero
	// values for Daily/Weekly/Weekday are rejected by the CEL rule in
	// scheduleSpecSchema (semantics undefined; date-anchored kinds don't
	// have a meaningful period offset distinct from a date shift).
	PeriodOffset *int `json:"periodOffset,omitempty"`
	// AutoAbortPrior is an opt-in flag (default false when unset) marking
	// this Schedule as one whose prior-period instance MAY be auto-aborted
	// by the downstream task-controller when the next instance materializes.
	// A pointer so an unset field (nil → effective false) is distinguishable
	// from an explicit false. The publisher resolves the pointer to a plain
	// bool and stamps it as the `auto_abort_prior` frontmatter key on every
	// materialized task; the controller reads that key as its eligibility
	// gate (controller-side gate flip ships in a separate PR). Optional —
	// never required by the CRD schema.
	AutoAbortPrior *bool `json:"autoAbortPrior,omitempty"`
}

// ScheduleTriggerApplyConfiguration constructs a declarative configuration of the ScheduleTrigger type for use with
// apply.
func ScheduleTrigger() *ScheduleTriggerApplyConfiguration {
	return &ScheduleTriggerApplyConfiguration{}
}

// WithRecurrence sets the Recurrence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Recurrence field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithRecurrence(
	value string,
) *ScheduleTriggerApplyConfiguration {
	b.Recurrence = &value
	return b
}

// WithWeekday sets the Weekday field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weekday field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithWeekday(
	value string,
) *ScheduleTriggerApplyConfiguration {
	b.Weekday = &value
	return b
}

// WithWeekdays adds the given value to the Weekdays field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Weekdays field.
func (b *ScheduleTriggerApplyConfiguration) WithWeekdays(
	values ...string,
) *ScheduleTriggerApplyConfiguration {
	for i := range values {
		b.Weekdays = append(b.Weekdays, values[i])
	}
	return b
}

// WithPeriodOffset sets the PeriodOffset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeriodOffset field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithPeriodOffset(
	value int,
) *ScheduleTriggerApplyConfiguration {
	b.PeriodOffset = &value
	return b
}

// WithAutoAbortPrior sets the AutoAbortPrior field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoAbortPrior field is set to the value of the last call.
func (b *ScheduleTriggerApplyConfiguration) WithAutoAbortPrior(
	value bool,
) *ScheduleTriggerApplyConfiguration {
	b.AutoAbortPrior = &value
	return b
}
