{{- if and (not .Values.existingSecret) .Values.sentry.dsn }}
# Created only when no existingSecret is referenced AND a Sentry DSN is set.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: recurring-task-creator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recurring-task-creator.labels" . | nindent 4 }}
data:
  sentry-dsn: {{ .Values.sentry.dsn | b64enc | quote }}
{{- end }}
