/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	taskbenjaminborbedev1 "github.com/bborbe/recurring-task-creator/k8s/apis/task.benjamin-borbe.de/v1"
	applyconfigurationtaskbenjaminborbedev1 "github.com/bborbe/recurring-task-creator/k8s/client/applyconfiguration/task.benjamin-borbe.de/v1"
	scheme "github.com/bborbe/recurring-task-creator/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SchedulesGetter has a method to return a ScheduleInterface.
// A group's client should implement this interface.
type SchedulesGetter interface {
	Schedules(namespace string) ScheduleInterface
}

// ScheduleInterface has methods to work with Schedule resources.
type ScheduleInterface interface {
	Create(ctx context.Context, schedule *taskbenjaminborbedev1.Schedule, opts metav1.CreateOptions) (*taskbenjaminborbedev1.Schedule, error)
	Update(ctx context.Context, schedule *taskbenjaminborbedev1.Schedule, opts metav1.UpdateOptions) (*taskbenjaminborbedev1.Schedule, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*taskbenjaminborbedev1.Schedule, error)
	List(ctx context.Context, opts metav1.ListOptions) (*taskbenjaminborbedev1.ScheduleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *taskbenjaminborbedev1.Schedule, err error)
	Apply(ctx context.Context, schedule *applyconfigurationtaskbenjaminborbedev1.ScheduleApplyConfiguration, opts metav1.ApplyOptions) (result *taskbenjaminborbedev1.Schedule, err error)
	ScheduleExpansion
}

// schedules implements ScheduleInterface
type schedules struct {
	*gentype.ClientWithListAndApply[*taskbenjaminborbedev1.Schedule, *taskbenjaminborbedev1.ScheduleList, *applyconfigurationtaskbenjaminborbedev1.ScheduleApplyConfiguration]
}

// newSchedules returns a Schedules
func newSchedules(c *TaskV1Client, namespace string) *schedules {
	return &schedules{
		gentype.NewClientWithListAndApply[*taskbenjaminborbedev1.Schedule, *taskbenjaminborbedev1.ScheduleList, *applyconfigurationtaskbenjaminborbedev1.ScheduleApplyConfiguration](
			"schedules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *taskbenjaminborbedev1.Schedule { return &taskbenjaminborbedev1.Schedule{} },
			func() *taskbenjaminborbedev1.ScheduleList { return &taskbenjaminborbedev1.ScheduleList{} },
		),
	}
}
