apiVersion: v1
kind: Service
metadata:
  name: recurring-task-creator
  namespace: '{{ "NAMESPACE" | env }}'
  annotations:
    admin/port: '9090'
    admin/path: ''
spec:
  ports:
  - name: http
    port: 9090
  selector:
    app: recurring-task-creator
