apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recurring-task-creator-cleanup
  namespace: '{{ "NAMESPACE" | env }}'
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 1m"
    random: '{{ "RANDOM" | env }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recurring-task-creator-cleanup
  serviceName: recurring-task-creator-cleanup
  template:
    metadata:
      annotations:
        random: '{{ "RANDOM" | env }}'
      labels:
        app: recurring-task-creator-cleanup
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_type
                    operator: In
                    values:
                      - agent
      securityContext:
        fsGroup: 65534
      serviceAccountName: recurring-task-creator-cleanup
      containers:
        - name: service
          args:
            - -v={{"LOGLEVEL" | env}}
          env:
            - name: CLEANUP_CRON
              value: '{{ "CLEANUP_CRON" | env }}'
            - name: GIT_REST_URL
              value: '{{ "GIT_REST_URL" | env }}'
            - name: GATEWAY_SECRET
              value: '{{ "GATEWAY_SECRET" | env }}'
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: recurring-task-creator
            - name: SENTRY_PROXY
              value: '{{"SENTRY_PROXY_URL" | env}}'
            - name: TZ
              value: Europe/Berlin
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: '{{"DOCKER_REGISTRY" | env}}/recurring-task-creator-cleanup:{{"BRANCH" | env}}'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: docker-quant
      volumes:
        - name: tmp
          emptyDir: {}
  updateStrategy:
    type: RollingUpdate
