// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg/cleanup"
)

type CleanupVaultWriter struct {
	UpdateFileStub        func(context.Context, string, func([]byte) ([]byte, error)) error
	updateFileMutex       sync.RWMutex
	updateFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 func([]byte) ([]byte, error)
	}
	updateFileReturns struct {
		result1 error
	}
	updateFileReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CleanupVaultWriter) UpdateFile(arg1 context.Context, arg2 string, arg3 func([]byte) ([]byte, error)) error {
	fake.updateFileMutex.Lock()
	ret, specificReturn := fake.updateFileReturnsOnCall[len(fake.updateFileArgsForCall)]
	fake.updateFileArgsForCall = append(fake.updateFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 func([]byte) ([]byte, error)
	}{arg1, arg2, arg3})
	stub := fake.UpdateFileStub
	fakeReturns := fake.updateFileReturns
	fake.recordInvocation("UpdateFile", []interface{}{arg1, arg2, arg3})
	fake.updateFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CleanupVaultWriter) UpdateFileCallCount() int {
	fake.updateFileMutex.RLock()
	defer fake.updateFileMutex.RUnlock()
	return len(fake.updateFileArgsForCall)
}

func (fake *CleanupVaultWriter) UpdateFileCalls(stub func(context.Context, string, func([]byte) ([]byte, error)) error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = stub
}

func (fake *CleanupVaultWriter) UpdateFileArgsForCall(i int) (context.Context, string, func([]byte) ([]byte, error)) {
	fake.updateFileMutex.RLock()
	defer fake.updateFileMutex.RUnlock()
	argsForCall := fake.updateFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CleanupVaultWriter) UpdateFileReturns(result1 error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = nil
	fake.updateFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *CleanupVaultWriter) UpdateFileReturnsOnCall(i int, result1 error) {
	fake.updateFileMutex.Lock()
	defer fake.updateFileMutex.Unlock()
	fake.UpdateFileStub = nil
	if fake.updateFileReturnsOnCall == nil {
		fake.updateFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CleanupVaultWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CleanupVaultWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cleanup.VaultWriter = new(CleanupVaultWriter)
