// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg/cleanup"
)

type CleanupMetrics struct {
	IncSupersededStub        func(string, string)
	incSupersededMutex       sync.RWMutex
	incSupersededArgsForCall []struct {
		arg1 string
		arg2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CleanupMetrics) IncSuperseded(arg1 string, arg2 string) {
	fake.incSupersededMutex.Lock()
	fake.incSupersededArgsForCall = append(fake.incSupersededArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.IncSupersededStub
	fake.recordInvocation("IncSuperseded", []interface{}{arg1, arg2})
	fake.incSupersededMutex.Unlock()
	if stub != nil {
		fake.IncSupersededStub(arg1, arg2)
	}
}

func (fake *CleanupMetrics) IncSupersededCallCount() int {
	fake.incSupersededMutex.RLock()
	defer fake.incSupersededMutex.RUnlock()
	return len(fake.incSupersededArgsForCall)
}

func (fake *CleanupMetrics) IncSupersededCalls(stub func(string, string)) {
	fake.incSupersededMutex.Lock()
	defer fake.incSupersededMutex.Unlock()
	fake.IncSupersededStub = stub
}

func (fake *CleanupMetrics) IncSupersededArgsForCall(i int) (string, string) {
	fake.incSupersededMutex.RLock()
	defer fake.incSupersededMutex.RUnlock()
	argsForCall := fake.incSupersededArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CleanupMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CleanupMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cleanup.Metrics = new(CleanupMetrics)
