// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg"
)

type FakeK8sConnector struct {
	SetupCustomResourceDefinitionStub        func(context.Context) error
	setupCustomResourceDefinitionMutex       sync.RWMutex
	setupCustomResourceDefinitionArgsForCall []struct {
		arg1 context.Context
	}
	setupCustomResourceDefinitionReturns struct {
		result1 error
	}
	setupCustomResourceDefinitionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinition(arg1 context.Context) error {
	fake.setupCustomResourceDefinitionMutex.Lock()
	ret, specificReturn := fake.setupCustomResourceDefinitionReturnsOnCall[len(fake.setupCustomResourceDefinitionArgsForCall)]
	fake.setupCustomResourceDefinitionArgsForCall = append(fake.setupCustomResourceDefinitionArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SetupCustomResourceDefinitionStub
	fakeReturns := fake.setupCustomResourceDefinitionReturns
	fake.recordInvocation("SetupCustomResourceDefinition", []interface{}{arg1})
	fake.setupCustomResourceDefinitionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionCallCount() int {
	fake.setupCustomResourceDefinitionMutex.RLock()
	defer fake.setupCustomResourceDefinitionMutex.RUnlock()
	return len(fake.setupCustomResourceDefinitionArgsForCall)
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionCalls(stub func(context.Context) error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = stub
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionArgsForCall(i int) context.Context {
	fake.setupCustomResourceDefinitionMutex.RLock()
	defer fake.setupCustomResourceDefinitionMutex.RUnlock()
	argsForCall := fake.setupCustomResourceDefinitionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionReturns(result1 error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = nil
	fake.setupCustomResourceDefinitionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) SetupCustomResourceDefinitionReturnsOnCall(i int, result1 error) {
	fake.setupCustomResourceDefinitionMutex.Lock()
	defer fake.setupCustomResourceDefinitionMutex.Unlock()
	fake.SetupCustomResourceDefinitionStub = nil
	if fake.setupCustomResourceDefinitionReturnsOnCall == nil {
		fake.setupCustomResourceDefinitionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupCustomResourceDefinitionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeK8sConnector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeK8sConnector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.K8sConnector = new(FakeK8sConnector)
