// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	lib "github.com/bborbe/agent"
	"github.com/bborbe/recurring-task-creator/pkg/publisher"
	"github.com/bborbe/recurring-task-creator/pkg/schedule"
)

type PublisherFrontmatterFormatter struct {
	FormatStub        func(lib.TaskFrontmatter, string, schedule.Date, bool) lib.TaskFrontmatter
	formatMutex       sync.RWMutex
	formatArgsForCall []struct {
		arg1 lib.TaskFrontmatter
		arg2 string
		arg3 schedule.Date
		arg4 bool
	}
	formatReturns struct {
		result1 lib.TaskFrontmatter
	}
	formatReturnsOnCall map[int]struct {
		result1 lib.TaskFrontmatter
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PublisherFrontmatterFormatter) Format(arg1 lib.TaskFrontmatter, arg2 string, arg3 schedule.Date, arg4 bool) lib.TaskFrontmatter {
	fake.formatMutex.Lock()
	ret, specificReturn := fake.formatReturnsOnCall[len(fake.formatArgsForCall)]
	fake.formatArgsForCall = append(fake.formatArgsForCall, struct {
		arg1 lib.TaskFrontmatter
		arg2 string
		arg3 schedule.Date
		arg4 bool
	}{arg1, arg2, arg3, arg4})
	stub := fake.FormatStub
	fakeReturns := fake.formatReturns
	fake.recordInvocation("Format", []interface{}{arg1, arg2, arg3, arg4})
	fake.formatMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PublisherFrontmatterFormatter) FormatCallCount() int {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	return len(fake.formatArgsForCall)
}

func (fake *PublisherFrontmatterFormatter) FormatCalls(stub func(lib.TaskFrontmatter, string, schedule.Date, bool) lib.TaskFrontmatter) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = stub
}

func (fake *PublisherFrontmatterFormatter) FormatArgsForCall(i int) (lib.TaskFrontmatter, string, schedule.Date, bool) {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	argsForCall := fake.formatArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *PublisherFrontmatterFormatter) FormatReturns(result1 lib.TaskFrontmatter) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	fake.formatReturns = struct {
		result1 lib.TaskFrontmatter
	}{result1}
}

func (fake *PublisherFrontmatterFormatter) FormatReturnsOnCall(i int, result1 lib.TaskFrontmatter) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	if fake.formatReturnsOnCall == nil {
		fake.formatReturnsOnCall = make(map[int]struct {
			result1 lib.TaskFrontmatter
		})
	}
	fake.formatReturnsOnCall[i] = struct {
		result1 lib.TaskFrontmatter
	}{result1}
}

func (fake *PublisherFrontmatterFormatter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PublisherFrontmatterFormatter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.FrontmatterFormatter = new(PublisherFrontmatterFormatter)
