// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	lib "github.com/bborbe/agent"
	"github.com/bborbe/recurring-task-creator/pkg/publisher"
	"github.com/bborbe/recurring-task-creator/pkg/schedule"
)

type PublisherTaskIdentifierCreator struct {
	CreateStub        func(context.Context, schedule.TaskDefinition, schedule.Date) (lib.TaskIdentifier, publisher.PeriodToken, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 schedule.TaskDefinition
		arg3 schedule.Date
	}
	createReturns struct {
		result1 lib.TaskIdentifier
		result2 publisher.PeriodToken
		result3 error
	}
	createReturnsOnCall map[int]struct {
		result1 lib.TaskIdentifier
		result2 publisher.PeriodToken
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PublisherTaskIdentifierCreator) Create(arg1 context.Context, arg2 schedule.TaskDefinition, arg3 schedule.Date) (lib.TaskIdentifier, publisher.PeriodToken, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 schedule.TaskDefinition
		arg3 schedule.Date
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *PublisherTaskIdentifierCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *PublisherTaskIdentifierCreator) CreateCalls(stub func(context.Context, schedule.TaskDefinition, schedule.Date) (lib.TaskIdentifier, publisher.PeriodToken, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *PublisherTaskIdentifierCreator) CreateArgsForCall(i int) (context.Context, schedule.TaskDefinition, schedule.Date) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PublisherTaskIdentifierCreator) CreateReturns(result1 lib.TaskIdentifier, result2 publisher.PeriodToken, result3 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 lib.TaskIdentifier
		result2 publisher.PeriodToken
		result3 error
	}{result1, result2, result3}
}

func (fake *PublisherTaskIdentifierCreator) CreateReturnsOnCall(i int, result1 lib.TaskIdentifier, result2 publisher.PeriodToken, result3 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 lib.TaskIdentifier
			result2 publisher.PeriodToken
			result3 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 lib.TaskIdentifier
		result2 publisher.PeriodToken
		result3 error
	}{result1, result2, result3}
}

func (fake *PublisherTaskIdentifierCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PublisherTaskIdentifierCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.TaskIdentifierCreator = new(PublisherTaskIdentifierCreator)
