// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg/publisher"
	"github.com/bborbe/recurring-task-creator/pkg/schedule"
)

type PublisherPeriodTokenBuilder struct {
	BuildStub        func(context.Context, schedule.TaskDefinition, schedule.Date) (publisher.PeriodToken, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 context.Context
		arg2 schedule.TaskDefinition
		arg3 schedule.Date
	}
	buildReturns struct {
		result1 publisher.PeriodToken
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 publisher.PeriodToken
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PublisherPeriodTokenBuilder) Build(arg1 context.Context, arg2 schedule.TaskDefinition, arg3 schedule.Date) (publisher.PeriodToken, error) {
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 context.Context
		arg2 schedule.TaskDefinition
		arg3 schedule.Date
	}{arg1, arg2, arg3})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2, arg3})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PublisherPeriodTokenBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *PublisherPeriodTokenBuilder) BuildCalls(stub func(context.Context, schedule.TaskDefinition, schedule.Date) (publisher.PeriodToken, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *PublisherPeriodTokenBuilder) BuildArgsForCall(i int) (context.Context, schedule.TaskDefinition, schedule.Date) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PublisherPeriodTokenBuilder) BuildReturns(result1 publisher.PeriodToken, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 publisher.PeriodToken
		result2 error
	}{result1, result2}
}

func (fake *PublisherPeriodTokenBuilder) BuildReturnsOnCall(i int, result1 publisher.PeriodToken, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 publisher.PeriodToken
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 publisher.PeriodToken
		result2 error
	}{result1, result2}
}

func (fake *PublisherPeriodTokenBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PublisherPeriodTokenBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.PeriodTokenBuilder = new(PublisherPeriodTokenBuilder)
