// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg/tick"
)

type TickMetrics struct {
	IncPublishedStub        func(string, string)
	incPublishedMutex       sync.RWMutex
	incPublishedArgsForCall []struct {
		arg1 string
		arg2 string
	}
	SetLastTickTimestampStub        func(float64)
	setLastTickTimestampMutex       sync.RWMutex
	setLastTickTimestampArgsForCall []struct {
		arg1 float64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TickMetrics) IncPublished(arg1 string, arg2 string) {
	fake.incPublishedMutex.Lock()
	fake.incPublishedArgsForCall = append(fake.incPublishedArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.IncPublishedStub
	fake.recordInvocation("IncPublished", []interface{}{arg1, arg2})
	fake.incPublishedMutex.Unlock()
	if stub != nil {
		fake.IncPublishedStub(arg1, arg2)
	}
}

func (fake *TickMetrics) IncPublishedCallCount() int {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	return len(fake.incPublishedArgsForCall)
}

func (fake *TickMetrics) IncPublishedCalls(stub func(string, string)) {
	fake.incPublishedMutex.Lock()
	defer fake.incPublishedMutex.Unlock()
	fake.IncPublishedStub = stub
}

func (fake *TickMetrics) IncPublishedArgsForCall(i int) (string, string) {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	argsForCall := fake.incPublishedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TickMetrics) SetLastTickTimestamp(arg1 float64) {
	fake.setLastTickTimestampMutex.Lock()
	fake.setLastTickTimestampArgsForCall = append(fake.setLastTickTimestampArgsForCall, struct {
		arg1 float64
	}{arg1})
	stub := fake.SetLastTickTimestampStub
	fake.recordInvocation("SetLastTickTimestamp", []interface{}{arg1})
	fake.setLastTickTimestampMutex.Unlock()
	if stub != nil {
		fake.SetLastTickTimestampStub(arg1)
	}
}

func (fake *TickMetrics) SetLastTickTimestampCallCount() int {
	fake.setLastTickTimestampMutex.RLock()
	defer fake.setLastTickTimestampMutex.RUnlock()
	return len(fake.setLastTickTimestampArgsForCall)
}

func (fake *TickMetrics) SetLastTickTimestampCalls(stub func(float64)) {
	fake.setLastTickTimestampMutex.Lock()
	defer fake.setLastTickTimestampMutex.Unlock()
	fake.SetLastTickTimestampStub = stub
}

func (fake *TickMetrics) SetLastTickTimestampArgsForCall(i int) float64 {
	fake.setLastTickTimestampMutex.RLock()
	defer fake.setLastTickTimestampMutex.RUnlock()
	argsForCall := fake.setLastTickTimestampArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TickMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TickMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ tick.Metrics = new(TickMetrics)
