// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/recurring-task-creator/pkg/tick"
)

type TickTick struct {
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	RunOnceStub        func(context.Context) error
	runOnceMutex       sync.RWMutex
	runOnceArgsForCall []struct {
		arg1 context.Context
	}
	runOnceReturns struct {
		result1 error
	}
	runOnceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TickTick) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TickTick) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *TickTick) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *TickTick) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TickTick) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *TickTick) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TickTick) RunOnce(arg1 context.Context) error {
	fake.runOnceMutex.Lock()
	ret, specificReturn := fake.runOnceReturnsOnCall[len(fake.runOnceArgsForCall)]
	fake.runOnceArgsForCall = append(fake.runOnceArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunOnceStub
	fakeReturns := fake.runOnceReturns
	fake.recordInvocation("RunOnce", []interface{}{arg1})
	fake.runOnceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TickTick) RunOnceCallCount() int {
	fake.runOnceMutex.RLock()
	defer fake.runOnceMutex.RUnlock()
	return len(fake.runOnceArgsForCall)
}

func (fake *TickTick) RunOnceCalls(stub func(context.Context) error) {
	fake.runOnceMutex.Lock()
	defer fake.runOnceMutex.Unlock()
	fake.RunOnceStub = stub
}

func (fake *TickTick) RunOnceArgsForCall(i int) context.Context {
	fake.runOnceMutex.RLock()
	defer fake.runOnceMutex.RUnlock()
	argsForCall := fake.runOnceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TickTick) RunOnceReturns(result1 error) {
	fake.runOnceMutex.Lock()
	defer fake.runOnceMutex.Unlock()
	fake.RunOnceStub = nil
	fake.runOnceReturns = struct {
		result1 error
	}{result1}
}

func (fake *TickTick) RunOnceReturnsOnCall(i int, result1 error) {
	fake.runOnceMutex.Lock()
	defer fake.runOnceMutex.Unlock()
	fake.RunOnceStub = nil
	if fake.runOnceReturnsOnCall == nil {
		fake.runOnceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runOnceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TickTick) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TickTick) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ tick.Tick = new(TickTick)
