apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: backup-atlassian-jira
spec:
  vault: personal
  title: Atlassian Jira Backup
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [Atlassian Jira Backup](https://borbe.atlassian.net/secure/admin/CloudExport.jspa)

      Save to: smb://hell.hm.benjamin-borbe.de/bborbe/Backups/Atlassian-Cloud/
