apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: backup-atlassian-confluence
spec:
  vault: personal
  title: Atlassian Confluence Backup
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [Atlassian Confluence Backup](https://borbe.atlassian.net/wiki/plugins/servlet/ondemandbackupmanager/admin)

      Save to: smb://hell.hm.benjamin-borbe.de/bborbe/Backups/Atlassian-Cloud/
