apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: check-bot-is-healthy
spec:
  vault: personal
  title: Bot is Healthy
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      check bot is ready for trading on monday

      * kubectlquant get po --all-namespaces|grep -v Running|grep -v Complete
      * [Prometheus Alerts](https://prometheus.quant.benjamin-borbe.de/alerts)
      * [Karma Active Alerts](https://karma.quant.benjamin-borbe.de/?q=%40state%3Dactive)
