apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: complete-longhorn-backups
spec:
  vault: personal
  title: Complete Longhorn Backups
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      [Longhorn Volumes](https://longhorn.quant.benjamin-borbe.de/#/volume)
