apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: complete-rsync-backups
spec:
  vault: personal
  title: Complete Rsync Backups
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      * check backup status
      ** [Backup Status](https://backup.hell.hm.benjamin-borbe.de/status)
