apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: docker-registry-gc
spec:
  vault: personal
  title: Docker Registry GC
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      Run garbage collection on docker registry to free storage space.

      kubectlquant -n docker-registry get pods

      kubectlquant -n docker-registry exec -it <POD_NAME> -- registry garbage-collect /etc/docker/registry/config.yml
