apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: home-assistant-update-backup
spec:
  vault: personal
  title: Home Assistant Update + Backup
  schedule:
    recurrence: Weekday
    weekday: Saturday
  template:
    body: |-
      Weekly Home Assistant maintenance.

      Steps:

      1. Login
      2. Create backup
      3. Download backup
      4. Update all

      [Home Assistant](http://homeassistant.local:8123/config/dashboard)
