apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-atlassian-confluence.yaml
  - backup-atlassian-jira.yaml
  - backup-google-drive.yaml
  - backup-pictures.yaml
  - capitalcom-apikey-dev.yaml
  - capitalcom-apikey-prod.yaml
  - check-bot-is-healthy.yaml
  - check-ftmo-demo-accounts.yaml
  - complete-longhorn-backups.yaml
  - complete-rsync-backups.yaml
  - docker-registry-gc.yaml
  - home-assistant-update-backup.yaml
  - lexoffice-invoices.yaml
  - moneymoney-review.yaml
  - monthly-review.yaml
  - opnsense-update.yaml
  - plan-month.yaml
  - plan-next-week.yaml
  - plan-year.yaml
  - quarter-plan.yaml
  - quarter-review.yaml
  - rebuild-trading-dev-prod.yaml
  - renew-gmail-oauth-tokens.yaml
  - run-update-all-saturday.yaml
  - run-update-all.yaml
  - shutdown-k3s.yaml
  - topic-backup-saturday.yaml
  - trading-profits.yaml
  - turn-off-fire.yaml
  - turn-off-hell.yaml
  - turn-off-sun.yaml
  - turn-on-hell.yaml
  - update-finances.yaml
  - update-frontend.yaml
  - update-go-mod.yaml
  - update-inventar.yaml
  - update-journal.yaml
  - update-k3s.yaml
  - update-library.yaml
  - update-minio.yaml
  - update-poste.yaml
  - update-screego.yaml
  - weekly-review.yaml
  - world-apply.yaml
  - yearly-review.yaml
