apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: plan-month
spec:
  vault: personal
  title: Plan Month
  schedule:
    recurrence: Monthly
  template:
    body: |-
      Create plan for month {{month}}

      In Obsidian run:

      /plan-month
