apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: plan-year
spec:
  vault: personal
  title: Plan Year
  schedule:
    recurrence: Yearly
  template:
    body: |-
      Create plan for year {{year}}

      In Obsidian run:

      /plan-year
