apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: quarter-plan
spec:
  vault: personal
  title: Plan Quarter
  schedule:
    recurrence: Quarterly
  template:
    body: |-
      Create plan for quarter {{quarter}}

      In Obsidian run:

      /plan-quarter
