apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: run-update-all
spec:
  vault: personal
  title: Run update-all.sh
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      Run system updates across all servers

      /Users/bborbe/Documents/workspaces/scripts/update-all.sh
