apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: trading-profits
spec:
  vault: personal
  title: Add Trading Profits to Sheet
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [Trading Profits Sheet](https://docs.google.com/spreadsheets/d/1F6ObbGvRciK4ZdvB3BuRCf7LJFWdL-46teXvXlR0waI/edit?usp=sharing)
