apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: turn-off-hell
spec:
  vault: personal
  title: Turn off hell
  schedule:
    recurrence: Weekday
    weekday: Sunday
  template:
    body: |-
      power off hell
