apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-poste
spec:
  vault: personal
  title: Update Poste
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [Poste Docker Hub](https://hub.docker.com/r/analogic/poste.io/tags)

      cat ~/Documents/workspaces/world/configuration/world.go|grep poste

      # update poste version in world.go

      make install

      world apply -a poste -v=2
