apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-finances
spec:
  vault: personal
  title: Update Finances spreadsheet
  schedule:
    recurrence: Monthly
  template:
    body: |-
      Fill spreadsheet at 5. of each month

      [Finances Spreadsheet](https://docs.google.com/spreadsheets/d/1Bmj_zmpomXJHW5sRTIcEE0xolIlGrYtO0FkY3nrxkPc/edit?usp=sharing)
