apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-go-mod
spec:
  vault: personal
  title: Update Trading Bot Dependencies
  schedule:
    recurrence: Monthly
  template:
    body: |-
      Update all dependencies of all trading services.

      Done when: All projects updated, tests pass, changes merged to master.

      [Updater Guide](obsidian://open?vault=Personal&file=50%20Knowledge%20Base%2FUpdater%20Guide)
