apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-screego
spec:
  vault: personal
  title: Update Screego
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [Screego Docker Hub](https://hub.docker.com/r/screego/server/tags)

      cat ~/Documents/workspaces/world/configuration/world.go|grep screego
