apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-frontend
spec:
  vault: personal
  title: Update Frontend
  schedule:
    recurrence: Monthly
  template:
    body: |-
      Follow Frontend Update Guide in Obsidian vault.

      Guide location: 50 Knowledge Base/Frontend Update Guide.md

      [Verification](https://prod.quant.benjamin-borbe.de/chart?epic=BTCUSD&broker=capitalcom&source=standard&bidAsk=bid&resolution=1m&from=NOW-7d&until=NOW)
