apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: update-k3s
spec:
  vault: personal
  title: Update K3s
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [K3s Release Channels](https://update.k3s.io/v1-release/channels)

      [K3s Upgrade Guide](obsidian://open?vault=Personal&file=50%20Knowledge%20Base%2FK3s%20Upgrade)

      * Update Hell
      * Update Nuke
