apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: world-apply
spec:
  vault: personal
  title: World apply
  schedule:
    recurrence: Monthly
  template:
    body: |-
      [World Apply Guide](obsidian://open?vault=Personal&file=50%20Knowledge%20Base%2FWorld%20Apply%20Guide)
