apiVersion: task.benjamin-borbe.de/v1
kind: Schedule
metadata:
  name: yearly-review
spec:
  vault: personal
  title: Review Year
  schedule:
    recurrence: Yearly
  template:
    body: |-
      Create review for year {{last-year}}

      In Obsidian run:

      /yearly-trading-review {{last-year}}
